/** THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
 * BY HAND!!
 *
 * Generated by lcm-gen
 **/

#include <string.h>
#include "lcmt_hubo_jointcommand.h"

static int __lcmt_hubo_jointcommand_hash_computed;
static int64_t __lcmt_hubo_jointcommand_hash;

int64_t __lcmt_hubo_jointcommand_hash_recursive(const __lcm_hash_ptr *p)
{
    const __lcm_hash_ptr *fp;
    for (fp = p; fp != NULL; fp = fp->parent)
        if (fp->v == __lcmt_hubo_jointcommand_get_hash)
            return 0;

    const __lcm_hash_ptr cp = { p, (void*)__lcmt_hubo_jointcommand_get_hash };
    (void) cp;

    int64_t hash = 0xf44e1915d869d6b4LL
         + __int64_t_hash_recursive(&cp)
         + __double_hash_recursive(&cp)
         + __double_hash_recursive(&cp)
         + __double_hash_recursive(&cp)
         + __double_hash_recursive(&cp)
         + __double_hash_recursive(&cp)
         + __double_hash_recursive(&cp)
         + __double_hash_recursive(&cp)
         + __double_hash_recursive(&cp)
         + __double_hash_recursive(&cp)
         + __double_hash_recursive(&cp)
         + __double_hash_recursive(&cp)
         + __double_hash_recursive(&cp)
         + __double_hash_recursive(&cp)
         + __double_hash_recursive(&cp)
         + __double_hash_recursive(&cp)
         + __double_hash_recursive(&cp)
         + __double_hash_recursive(&cp)
         + __double_hash_recursive(&cp)
         + __double_hash_recursive(&cp)
         + __double_hash_recursive(&cp)
         + __double_hash_recursive(&cp)
         + __double_hash_recursive(&cp)
         + __double_hash_recursive(&cp)
         + __double_hash_recursive(&cp)
         + __double_hash_recursive(&cp)
         + __double_hash_recursive(&cp)
         + __double_hash_recursive(&cp)
         + __double_hash_recursive(&cp)
         + __double_hash_recursive(&cp)
         + __double_hash_recursive(&cp)
        ;

    return (hash<<1) + ((hash>>63)&1);
}

int64_t __lcmt_hubo_jointcommand_get_hash(void)
{
    if (!__lcmt_hubo_jointcommand_hash_computed) {
        __lcmt_hubo_jointcommand_hash = __lcmt_hubo_jointcommand_hash_recursive(NULL);
        __lcmt_hubo_jointcommand_hash_computed = 1;
    }

    return __lcmt_hubo_jointcommand_hash;
}

int __lcmt_hubo_jointcommand_encode_array(void *buf, int offset, int maxlen, const lcmt_hubo_jointcommand *p, int elements)
{
    int pos = 0, thislen, element;

    for (element = 0; element < elements; element++) {

        thislen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].timestamp), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_encode_array(buf, offset + pos, maxlen - pos, &(p[element].HipYaw), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_encode_array(buf, offset + pos, maxlen - pos, &(p[element].HY), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_encode_array(buf, offset + pos, maxlen - pos, &(p[element].HR), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_encode_array(buf, offset + pos, maxlen - pos, &(p[element].HP), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_encode_array(buf, offset + pos, maxlen - pos, &(p[element].JC_LSP), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_encode_array(buf, offset + pos, maxlen - pos, &(p[element].JC_LSR), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_encode_array(buf, offset + pos, maxlen - pos, &(p[element].JC_LSY), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_encode_array(buf, offset + pos, maxlen - pos, &(p[element].JC_LEP), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_encode_array(buf, offset + pos, maxlen - pos, &(p[element].JC_LWY), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_encode_array(buf, offset + pos, maxlen - pos, &(p[element].JC_LWR), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_encode_array(buf, offset + pos, maxlen - pos, &(p[element].JC_LWP), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_encode_array(buf, offset + pos, maxlen - pos, &(p[element].JC_RSP), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_encode_array(buf, offset + pos, maxlen - pos, &(p[element].JC_RSR), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_encode_array(buf, offset + pos, maxlen - pos, &(p[element].JC_RSY), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_encode_array(buf, offset + pos, maxlen - pos, &(p[element].JC_REP), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_encode_array(buf, offset + pos, maxlen - pos, &(p[element].JC_RWY), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_encode_array(buf, offset + pos, maxlen - pos, &(p[element].JC_RWR), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_encode_array(buf, offset + pos, maxlen - pos, &(p[element].JC_RWP), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_encode_array(buf, offset + pos, maxlen - pos, &(p[element].JC_LHY), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_encode_array(buf, offset + pos, maxlen - pos, &(p[element].JC_LHR), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_encode_array(buf, offset + pos, maxlen - pos, &(p[element].JC_LHP), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_encode_array(buf, offset + pos, maxlen - pos, &(p[element].JC_LKP), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_encode_array(buf, offset + pos, maxlen - pos, &(p[element].JC_LAP), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_encode_array(buf, offset + pos, maxlen - pos, &(p[element].JC_LAR), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_encode_array(buf, offset + pos, maxlen - pos, &(p[element].JC_RHY), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_encode_array(buf, offset + pos, maxlen - pos, &(p[element].JC_RHR), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_encode_array(buf, offset + pos, maxlen - pos, &(p[element].JC_RHP), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_encode_array(buf, offset + pos, maxlen - pos, &(p[element].JC_RKP), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_encode_array(buf, offset + pos, maxlen - pos, &(p[element].JC_RAP), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_encode_array(buf, offset + pos, maxlen - pos, &(p[element].JC_RAR), 1);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int lcmt_hubo_jointcommand_encode(void *buf, int offset, int maxlen, const lcmt_hubo_jointcommand *p)
{
    int pos = 0, thislen;
    int64_t hash = __lcmt_hubo_jointcommand_get_hash();

    thislen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    thislen = __lcmt_hubo_jointcommand_encode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int __lcmt_hubo_jointcommand_encoded_array_size(const lcmt_hubo_jointcommand *p, int elements)
{
    int size = 0, element;
    for (element = 0; element < elements; element++) {

        size += __int64_t_encoded_array_size(&(p[element].timestamp), 1);

        size += __double_encoded_array_size(&(p[element].HipYaw), 1);

        size += __double_encoded_array_size(&(p[element].HY), 1);

        size += __double_encoded_array_size(&(p[element].HR), 1);

        size += __double_encoded_array_size(&(p[element].HP), 1);

        size += __double_encoded_array_size(&(p[element].JC_LSP), 1);

        size += __double_encoded_array_size(&(p[element].JC_LSR), 1);

        size += __double_encoded_array_size(&(p[element].JC_LSY), 1);

        size += __double_encoded_array_size(&(p[element].JC_LEP), 1);

        size += __double_encoded_array_size(&(p[element].JC_LWY), 1);

        size += __double_encoded_array_size(&(p[element].JC_LWR), 1);

        size += __double_encoded_array_size(&(p[element].JC_LWP), 1);

        size += __double_encoded_array_size(&(p[element].JC_RSP), 1);

        size += __double_encoded_array_size(&(p[element].JC_RSR), 1);

        size += __double_encoded_array_size(&(p[element].JC_RSY), 1);

        size += __double_encoded_array_size(&(p[element].JC_REP), 1);

        size += __double_encoded_array_size(&(p[element].JC_RWY), 1);

        size += __double_encoded_array_size(&(p[element].JC_RWR), 1);

        size += __double_encoded_array_size(&(p[element].JC_RWP), 1);

        size += __double_encoded_array_size(&(p[element].JC_LHY), 1);

        size += __double_encoded_array_size(&(p[element].JC_LHR), 1);

        size += __double_encoded_array_size(&(p[element].JC_LHP), 1);

        size += __double_encoded_array_size(&(p[element].JC_LKP), 1);

        size += __double_encoded_array_size(&(p[element].JC_LAP), 1);

        size += __double_encoded_array_size(&(p[element].JC_LAR), 1);

        size += __double_encoded_array_size(&(p[element].JC_RHY), 1);

        size += __double_encoded_array_size(&(p[element].JC_RHR), 1);

        size += __double_encoded_array_size(&(p[element].JC_RHP), 1);

        size += __double_encoded_array_size(&(p[element].JC_RKP), 1);

        size += __double_encoded_array_size(&(p[element].JC_RAP), 1);

        size += __double_encoded_array_size(&(p[element].JC_RAR), 1);

    }
    return size;
}

int lcmt_hubo_jointcommand_encoded_size(const lcmt_hubo_jointcommand *p)
{
    return 8 + __lcmt_hubo_jointcommand_encoded_array_size(p, 1);
}

int __lcmt_hubo_jointcommand_decode_array(const void *buf, int offset, int maxlen, lcmt_hubo_jointcommand *p, int elements)
{
    int pos = 0, thislen, element;

    for (element = 0; element < elements; element++) {

        thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].timestamp), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_decode_array(buf, offset + pos, maxlen - pos, &(p[element].HipYaw), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_decode_array(buf, offset + pos, maxlen - pos, &(p[element].HY), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_decode_array(buf, offset + pos, maxlen - pos, &(p[element].HR), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_decode_array(buf, offset + pos, maxlen - pos, &(p[element].HP), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_decode_array(buf, offset + pos, maxlen - pos, &(p[element].JC_LSP), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_decode_array(buf, offset + pos, maxlen - pos, &(p[element].JC_LSR), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_decode_array(buf, offset + pos, maxlen - pos, &(p[element].JC_LSY), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_decode_array(buf, offset + pos, maxlen - pos, &(p[element].JC_LEP), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_decode_array(buf, offset + pos, maxlen - pos, &(p[element].JC_LWY), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_decode_array(buf, offset + pos, maxlen - pos, &(p[element].JC_LWR), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_decode_array(buf, offset + pos, maxlen - pos, &(p[element].JC_LWP), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_decode_array(buf, offset + pos, maxlen - pos, &(p[element].JC_RSP), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_decode_array(buf, offset + pos, maxlen - pos, &(p[element].JC_RSR), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_decode_array(buf, offset + pos, maxlen - pos, &(p[element].JC_RSY), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_decode_array(buf, offset + pos, maxlen - pos, &(p[element].JC_REP), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_decode_array(buf, offset + pos, maxlen - pos, &(p[element].JC_RWY), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_decode_array(buf, offset + pos, maxlen - pos, &(p[element].JC_RWR), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_decode_array(buf, offset + pos, maxlen - pos, &(p[element].JC_RWP), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_decode_array(buf, offset + pos, maxlen - pos, &(p[element].JC_LHY), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_decode_array(buf, offset + pos, maxlen - pos, &(p[element].JC_LHR), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_decode_array(buf, offset + pos, maxlen - pos, &(p[element].JC_LHP), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_decode_array(buf, offset + pos, maxlen - pos, &(p[element].JC_LKP), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_decode_array(buf, offset + pos, maxlen - pos, &(p[element].JC_LAP), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_decode_array(buf, offset + pos, maxlen - pos, &(p[element].JC_LAR), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_decode_array(buf, offset + pos, maxlen - pos, &(p[element].JC_RHY), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_decode_array(buf, offset + pos, maxlen - pos, &(p[element].JC_RHR), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_decode_array(buf, offset + pos, maxlen - pos, &(p[element].JC_RHP), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_decode_array(buf, offset + pos, maxlen - pos, &(p[element].JC_RKP), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_decode_array(buf, offset + pos, maxlen - pos, &(p[element].JC_RAP), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_decode_array(buf, offset + pos, maxlen - pos, &(p[element].JC_RAR), 1);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int __lcmt_hubo_jointcommand_decode_array_cleanup(lcmt_hubo_jointcommand *p, int elements)
{
    int element;
    for (element = 0; element < elements; element++) {

        __int64_t_decode_array_cleanup(&(p[element].timestamp), 1);

        __double_decode_array_cleanup(&(p[element].HipYaw), 1);

        __double_decode_array_cleanup(&(p[element].HY), 1);

        __double_decode_array_cleanup(&(p[element].HR), 1);

        __double_decode_array_cleanup(&(p[element].HP), 1);

        __double_decode_array_cleanup(&(p[element].JC_LSP), 1);

        __double_decode_array_cleanup(&(p[element].JC_LSR), 1);

        __double_decode_array_cleanup(&(p[element].JC_LSY), 1);

        __double_decode_array_cleanup(&(p[element].JC_LEP), 1);

        __double_decode_array_cleanup(&(p[element].JC_LWY), 1);

        __double_decode_array_cleanup(&(p[element].JC_LWR), 1);

        __double_decode_array_cleanup(&(p[element].JC_LWP), 1);

        __double_decode_array_cleanup(&(p[element].JC_RSP), 1);

        __double_decode_array_cleanup(&(p[element].JC_RSR), 1);

        __double_decode_array_cleanup(&(p[element].JC_RSY), 1);

        __double_decode_array_cleanup(&(p[element].JC_REP), 1);

        __double_decode_array_cleanup(&(p[element].JC_RWY), 1);

        __double_decode_array_cleanup(&(p[element].JC_RWR), 1);

        __double_decode_array_cleanup(&(p[element].JC_RWP), 1);

        __double_decode_array_cleanup(&(p[element].JC_LHY), 1);

        __double_decode_array_cleanup(&(p[element].JC_LHR), 1);

        __double_decode_array_cleanup(&(p[element].JC_LHP), 1);

        __double_decode_array_cleanup(&(p[element].JC_LKP), 1);

        __double_decode_array_cleanup(&(p[element].JC_LAP), 1);

        __double_decode_array_cleanup(&(p[element].JC_LAR), 1);

        __double_decode_array_cleanup(&(p[element].JC_RHY), 1);

        __double_decode_array_cleanup(&(p[element].JC_RHR), 1);

        __double_decode_array_cleanup(&(p[element].JC_RHP), 1);

        __double_decode_array_cleanup(&(p[element].JC_RKP), 1);

        __double_decode_array_cleanup(&(p[element].JC_RAP), 1);

        __double_decode_array_cleanup(&(p[element].JC_RAR), 1);

    }
    return 0;
}

int lcmt_hubo_jointcommand_decode(const void *buf, int offset, int maxlen, lcmt_hubo_jointcommand *p)
{
    int pos = 0, thislen;
    int64_t hash = __lcmt_hubo_jointcommand_get_hash();

    int64_t this_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &this_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (this_hash != hash) return -1;

    thislen = __lcmt_hubo_jointcommand_decode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int lcmt_hubo_jointcommand_decode_cleanup(lcmt_hubo_jointcommand *p)
{
    return __lcmt_hubo_jointcommand_decode_array_cleanup(p, 1);
}

int __lcmt_hubo_jointcommand_clone_array(const lcmt_hubo_jointcommand *p, lcmt_hubo_jointcommand *q, int elements)
{
    int element;
    for (element = 0; element < elements; element++) {

        __int64_t_clone_array(&(p[element].timestamp), &(q[element].timestamp), 1);

        __double_clone_array(&(p[element].HipYaw), &(q[element].HipYaw), 1);

        __double_clone_array(&(p[element].HY), &(q[element].HY), 1);

        __double_clone_array(&(p[element].HR), &(q[element].HR), 1);

        __double_clone_array(&(p[element].HP), &(q[element].HP), 1);

        __double_clone_array(&(p[element].JC_LSP), &(q[element].JC_LSP), 1);

        __double_clone_array(&(p[element].JC_LSR), &(q[element].JC_LSR), 1);

        __double_clone_array(&(p[element].JC_LSY), &(q[element].JC_LSY), 1);

        __double_clone_array(&(p[element].JC_LEP), &(q[element].JC_LEP), 1);

        __double_clone_array(&(p[element].JC_LWY), &(q[element].JC_LWY), 1);

        __double_clone_array(&(p[element].JC_LWR), &(q[element].JC_LWR), 1);

        __double_clone_array(&(p[element].JC_LWP), &(q[element].JC_LWP), 1);

        __double_clone_array(&(p[element].JC_RSP), &(q[element].JC_RSP), 1);

        __double_clone_array(&(p[element].JC_RSR), &(q[element].JC_RSR), 1);

        __double_clone_array(&(p[element].JC_RSY), &(q[element].JC_RSY), 1);

        __double_clone_array(&(p[element].JC_REP), &(q[element].JC_REP), 1);

        __double_clone_array(&(p[element].JC_RWY), &(q[element].JC_RWY), 1);

        __double_clone_array(&(p[element].JC_RWR), &(q[element].JC_RWR), 1);

        __double_clone_array(&(p[element].JC_RWP), &(q[element].JC_RWP), 1);

        __double_clone_array(&(p[element].JC_LHY), &(q[element].JC_LHY), 1);

        __double_clone_array(&(p[element].JC_LHR), &(q[element].JC_LHR), 1);

        __double_clone_array(&(p[element].JC_LHP), &(q[element].JC_LHP), 1);

        __double_clone_array(&(p[element].JC_LKP), &(q[element].JC_LKP), 1);

        __double_clone_array(&(p[element].JC_LAP), &(q[element].JC_LAP), 1);

        __double_clone_array(&(p[element].JC_LAR), &(q[element].JC_LAR), 1);

        __double_clone_array(&(p[element].JC_RHY), &(q[element].JC_RHY), 1);

        __double_clone_array(&(p[element].JC_RHR), &(q[element].JC_RHR), 1);

        __double_clone_array(&(p[element].JC_RHP), &(q[element].JC_RHP), 1);

        __double_clone_array(&(p[element].JC_RKP), &(q[element].JC_RKP), 1);

        __double_clone_array(&(p[element].JC_RAP), &(q[element].JC_RAP), 1);

        __double_clone_array(&(p[element].JC_RAR), &(q[element].JC_RAR), 1);

    }
    return 0;
}

lcmt_hubo_jointcommand *lcmt_hubo_jointcommand_copy(const lcmt_hubo_jointcommand *p)
{
    lcmt_hubo_jointcommand *q = (lcmt_hubo_jointcommand*) malloc(sizeof(lcmt_hubo_jointcommand));
    __lcmt_hubo_jointcommand_clone_array(p, q, 1);
    return q;
}

void lcmt_hubo_jointcommand_destroy(lcmt_hubo_jointcommand *p)
{
    __lcmt_hubo_jointcommand_decode_array_cleanup(p, 1);
    free(p);
}

int lcmt_hubo_jointcommand_publish(lcm_t *lc, const char *channel, const lcmt_hubo_jointcommand *p)
{
      int max_data_size = lcmt_hubo_jointcommand_encoded_size (p);
      uint8_t *buf = (uint8_t*) malloc (max_data_size);
      if (!buf) return -1;
      int data_size = lcmt_hubo_jointcommand_encode (buf, 0, max_data_size, p);
      if (data_size < 0) {
          free (buf);
          return data_size;
      }
      int status = lcm_publish (lc, channel, buf, data_size);
      free (buf);
      return status;
}

struct _lcmt_hubo_jointcommand_subscription_t {
    lcmt_hubo_jointcommand_handler_t user_handler;
    void *userdata;
    lcm_subscription_t *lc_h;
};
static
void lcmt_hubo_jointcommand_handler_stub (const lcm_recv_buf_t *rbuf,
                            const char *channel, void *userdata)
{
    int status;
    lcmt_hubo_jointcommand p;
    memset(&p, 0, sizeof(lcmt_hubo_jointcommand));
    status = lcmt_hubo_jointcommand_decode (rbuf->data, 0, rbuf->data_size, &p);
    if (status < 0) {
        fprintf (stderr, "error %d decoding lcmt_hubo_jointcommand!!!\n", status);
        return;
    }

    lcmt_hubo_jointcommand_subscription_t *h = (lcmt_hubo_jointcommand_subscription_t*) userdata;
    h->user_handler (rbuf, channel, &p, h->userdata);

    lcmt_hubo_jointcommand_decode_cleanup (&p);
}

lcmt_hubo_jointcommand_subscription_t* lcmt_hubo_jointcommand_subscribe (lcm_t *lcm,
                    const char *channel,
                    lcmt_hubo_jointcommand_handler_t f, void *userdata)
{
    lcmt_hubo_jointcommand_subscription_t *n = (lcmt_hubo_jointcommand_subscription_t*)
                       malloc(sizeof(lcmt_hubo_jointcommand_subscription_t));
    n->user_handler = f;
    n->userdata = userdata;
    n->lc_h = lcm_subscribe (lcm, channel,
                                 lcmt_hubo_jointcommand_handler_stub, n);
    if (n->lc_h == NULL) {
        fprintf (stderr,"couldn't reg lcmt_hubo_jointcommand LCM handler!\n");
        free (n);
        return NULL;
    }
    return n;
}

int lcmt_hubo_jointcommand_subscription_set_queue_capacity (lcmt_hubo_jointcommand_subscription_t* subs,
                              int num_messages)
{
    return lcm_subscription_set_queue_capacity (subs->lc_h, num_messages);
}

int lcmt_hubo_jointcommand_unsubscribe(lcm_t *lcm, lcmt_hubo_jointcommand_subscription_t* hid)
{
    int status = lcm_unsubscribe (lcm, hid->lc_h);
    if (0 != status) {
        fprintf(stderr,
           "couldn't unsubscribe lcmt_hubo_jointcommand_handler %p!\n", hid);
        return -1;
    }
    free (hid);
    return 0;
}

