/** THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
 * BY HAND!!
 *
 * Generated by lcm-gen
 **/

#include <string.h>
#include "lcmt_hubo_saggital_state.h"

static int __lcmt_hubo_saggital_state_hash_computed;
static int64_t __lcmt_hubo_saggital_state_hash;

int64_t __lcmt_hubo_saggital_state_hash_recursive(const __lcm_hash_ptr *p)
{
    const __lcm_hash_ptr *fp;
    for (fp = p; fp != NULL; fp = fp->parent)
        if (fp->v == __lcmt_hubo_saggital_state_get_hash)
            return 0;

    const __lcm_hash_ptr cp = { p, (void*)__lcmt_hubo_saggital_state_get_hash };
    (void) cp;

    int64_t hash = 0x2a998968a52835e1LL
         + __int64_t_hash_recursive(&cp)
         + __double_hash_recursive(&cp)
         + __double_hash_recursive(&cp)
         + __double_hash_recursive(&cp)
         + __double_hash_recursive(&cp)
         + __double_hash_recursive(&cp)
         + __double_hash_recursive(&cp)
         + __double_hash_recursive(&cp)
         + __double_hash_recursive(&cp)
         + __double_hash_recursive(&cp)
         + __double_hash_recursive(&cp)
         + __double_hash_recursive(&cp)
         + __double_hash_recursive(&cp)
         + __double_hash_recursive(&cp)
         + __double_hash_recursive(&cp)
         + __double_hash_recursive(&cp)
         + __double_hash_recursive(&cp)
         + __double_hash_recursive(&cp)
         + __double_hash_recursive(&cp)
         + __double_hash_recursive(&cp)
         + __double_hash_recursive(&cp)
         + __double_hash_recursive(&cp)
         + __double_hash_recursive(&cp)
         + __double_hash_recursive(&cp)
         + __double_hash_recursive(&cp)
         + __double_hash_recursive(&cp)
         + __double_hash_recursive(&cp)
         + __double_hash_recursive(&cp)
         + __double_hash_recursive(&cp)
         + __double_hash_recursive(&cp)
         + __double_hash_recursive(&cp)
         + __double_hash_recursive(&cp)
         + __double_hash_recursive(&cp)
        ;

    return (hash<<1) + ((hash>>63)&1);
}

int64_t __lcmt_hubo_saggital_state_get_hash(void)
{
    if (!__lcmt_hubo_saggital_state_hash_computed) {
        __lcmt_hubo_saggital_state_hash = __lcmt_hubo_saggital_state_hash_recursive(NULL);
        __lcmt_hubo_saggital_state_hash_computed = 1;
    }

    return __lcmt_hubo_saggital_state_hash;
}

int __lcmt_hubo_saggital_state_encode_array(void *buf, int offset, int maxlen, const lcmt_hubo_saggital_state *p, int elements)
{
    int pos = 0, thislen, element;

    for (element = 0; element < elements; element++) {

        thislen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].timestamp), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_encode_array(buf, offset + pos, maxlen - pos, &(p[element].base_link_x), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_encode_array(buf, offset + pos, maxlen - pos, &(p[element].base_link_z), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_encode_array(buf, offset + pos, maxlen - pos, &(p[element].base_link_p), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_encode_array(buf, offset + pos, maxlen - pos, &(p[element].HP), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_encode_array(buf, offset + pos, maxlen - pos, &(p[element].LSP), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_encode_array(buf, offset + pos, maxlen - pos, &(p[element].LEP), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_encode_array(buf, offset + pos, maxlen - pos, &(p[element].LWP), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_encode_array(buf, offset + pos, maxlen - pos, &(p[element].RSP), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_encode_array(buf, offset + pos, maxlen - pos, &(p[element].REP), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_encode_array(buf, offset + pos, maxlen - pos, &(p[element].RWP), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_encode_array(buf, offset + pos, maxlen - pos, &(p[element].LHP), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_encode_array(buf, offset + pos, maxlen - pos, &(p[element].LKP), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_encode_array(buf, offset + pos, maxlen - pos, &(p[element].LAP), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_encode_array(buf, offset + pos, maxlen - pos, &(p[element].RHP), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_encode_array(buf, offset + pos, maxlen - pos, &(p[element].RKP), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_encode_array(buf, offset + pos, maxlen - pos, &(p[element].RAP), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_encode_array(buf, offset + pos, maxlen - pos, &(p[element].base_link_xdot), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_encode_array(buf, offset + pos, maxlen - pos, &(p[element].base_link_zdot), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_encode_array(buf, offset + pos, maxlen - pos, &(p[element].base_link_pdot), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_encode_array(buf, offset + pos, maxlen - pos, &(p[element].HPdot), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_encode_array(buf, offset + pos, maxlen - pos, &(p[element].LSPdot), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_encode_array(buf, offset + pos, maxlen - pos, &(p[element].LEPdot), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_encode_array(buf, offset + pos, maxlen - pos, &(p[element].LWPdot), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_encode_array(buf, offset + pos, maxlen - pos, &(p[element].RSPdot), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_encode_array(buf, offset + pos, maxlen - pos, &(p[element].REPdot), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_encode_array(buf, offset + pos, maxlen - pos, &(p[element].RWPdot), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_encode_array(buf, offset + pos, maxlen - pos, &(p[element].LHPdot), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_encode_array(buf, offset + pos, maxlen - pos, &(p[element].LKPdot), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_encode_array(buf, offset + pos, maxlen - pos, &(p[element].LAPdot), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_encode_array(buf, offset + pos, maxlen - pos, &(p[element].RHPdot), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_encode_array(buf, offset + pos, maxlen - pos, &(p[element].RKPdot), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_encode_array(buf, offset + pos, maxlen - pos, &(p[element].RAPdot), 1);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int lcmt_hubo_saggital_state_encode(void *buf, int offset, int maxlen, const lcmt_hubo_saggital_state *p)
{
    int pos = 0, thislen;
    int64_t hash = __lcmt_hubo_saggital_state_get_hash();

    thislen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    thislen = __lcmt_hubo_saggital_state_encode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int __lcmt_hubo_saggital_state_encoded_array_size(const lcmt_hubo_saggital_state *p, int elements)
{
    int size = 0, element;
    for (element = 0; element < elements; element++) {

        size += __int64_t_encoded_array_size(&(p[element].timestamp), 1);

        size += __double_encoded_array_size(&(p[element].base_link_x), 1);

        size += __double_encoded_array_size(&(p[element].base_link_z), 1);

        size += __double_encoded_array_size(&(p[element].base_link_p), 1);

        size += __double_encoded_array_size(&(p[element].HP), 1);

        size += __double_encoded_array_size(&(p[element].LSP), 1);

        size += __double_encoded_array_size(&(p[element].LEP), 1);

        size += __double_encoded_array_size(&(p[element].LWP), 1);

        size += __double_encoded_array_size(&(p[element].RSP), 1);

        size += __double_encoded_array_size(&(p[element].REP), 1);

        size += __double_encoded_array_size(&(p[element].RWP), 1);

        size += __double_encoded_array_size(&(p[element].LHP), 1);

        size += __double_encoded_array_size(&(p[element].LKP), 1);

        size += __double_encoded_array_size(&(p[element].LAP), 1);

        size += __double_encoded_array_size(&(p[element].RHP), 1);

        size += __double_encoded_array_size(&(p[element].RKP), 1);

        size += __double_encoded_array_size(&(p[element].RAP), 1);

        size += __double_encoded_array_size(&(p[element].base_link_xdot), 1);

        size += __double_encoded_array_size(&(p[element].base_link_zdot), 1);

        size += __double_encoded_array_size(&(p[element].base_link_pdot), 1);

        size += __double_encoded_array_size(&(p[element].HPdot), 1);

        size += __double_encoded_array_size(&(p[element].LSPdot), 1);

        size += __double_encoded_array_size(&(p[element].LEPdot), 1);

        size += __double_encoded_array_size(&(p[element].LWPdot), 1);

        size += __double_encoded_array_size(&(p[element].RSPdot), 1);

        size += __double_encoded_array_size(&(p[element].REPdot), 1);

        size += __double_encoded_array_size(&(p[element].RWPdot), 1);

        size += __double_encoded_array_size(&(p[element].LHPdot), 1);

        size += __double_encoded_array_size(&(p[element].LKPdot), 1);

        size += __double_encoded_array_size(&(p[element].LAPdot), 1);

        size += __double_encoded_array_size(&(p[element].RHPdot), 1);

        size += __double_encoded_array_size(&(p[element].RKPdot), 1);

        size += __double_encoded_array_size(&(p[element].RAPdot), 1);

    }
    return size;
}

int lcmt_hubo_saggital_state_encoded_size(const lcmt_hubo_saggital_state *p)
{
    return 8 + __lcmt_hubo_saggital_state_encoded_array_size(p, 1);
}

int __lcmt_hubo_saggital_state_decode_array(const void *buf, int offset, int maxlen, lcmt_hubo_saggital_state *p, int elements)
{
    int pos = 0, thislen, element;

    for (element = 0; element < elements; element++) {

        thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].timestamp), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_decode_array(buf, offset + pos, maxlen - pos, &(p[element].base_link_x), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_decode_array(buf, offset + pos, maxlen - pos, &(p[element].base_link_z), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_decode_array(buf, offset + pos, maxlen - pos, &(p[element].base_link_p), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_decode_array(buf, offset + pos, maxlen - pos, &(p[element].HP), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_decode_array(buf, offset + pos, maxlen - pos, &(p[element].LSP), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_decode_array(buf, offset + pos, maxlen - pos, &(p[element].LEP), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_decode_array(buf, offset + pos, maxlen - pos, &(p[element].LWP), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_decode_array(buf, offset + pos, maxlen - pos, &(p[element].RSP), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_decode_array(buf, offset + pos, maxlen - pos, &(p[element].REP), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_decode_array(buf, offset + pos, maxlen - pos, &(p[element].RWP), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_decode_array(buf, offset + pos, maxlen - pos, &(p[element].LHP), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_decode_array(buf, offset + pos, maxlen - pos, &(p[element].LKP), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_decode_array(buf, offset + pos, maxlen - pos, &(p[element].LAP), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_decode_array(buf, offset + pos, maxlen - pos, &(p[element].RHP), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_decode_array(buf, offset + pos, maxlen - pos, &(p[element].RKP), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_decode_array(buf, offset + pos, maxlen - pos, &(p[element].RAP), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_decode_array(buf, offset + pos, maxlen - pos, &(p[element].base_link_xdot), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_decode_array(buf, offset + pos, maxlen - pos, &(p[element].base_link_zdot), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_decode_array(buf, offset + pos, maxlen - pos, &(p[element].base_link_pdot), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_decode_array(buf, offset + pos, maxlen - pos, &(p[element].HPdot), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_decode_array(buf, offset + pos, maxlen - pos, &(p[element].LSPdot), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_decode_array(buf, offset + pos, maxlen - pos, &(p[element].LEPdot), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_decode_array(buf, offset + pos, maxlen - pos, &(p[element].LWPdot), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_decode_array(buf, offset + pos, maxlen - pos, &(p[element].RSPdot), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_decode_array(buf, offset + pos, maxlen - pos, &(p[element].REPdot), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_decode_array(buf, offset + pos, maxlen - pos, &(p[element].RWPdot), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_decode_array(buf, offset + pos, maxlen - pos, &(p[element].LHPdot), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_decode_array(buf, offset + pos, maxlen - pos, &(p[element].LKPdot), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_decode_array(buf, offset + pos, maxlen - pos, &(p[element].LAPdot), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_decode_array(buf, offset + pos, maxlen - pos, &(p[element].RHPdot), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_decode_array(buf, offset + pos, maxlen - pos, &(p[element].RKPdot), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_decode_array(buf, offset + pos, maxlen - pos, &(p[element].RAPdot), 1);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int __lcmt_hubo_saggital_state_decode_array_cleanup(lcmt_hubo_saggital_state *p, int elements)
{
    int element;
    for (element = 0; element < elements; element++) {

        __int64_t_decode_array_cleanup(&(p[element].timestamp), 1);

        __double_decode_array_cleanup(&(p[element].base_link_x), 1);

        __double_decode_array_cleanup(&(p[element].base_link_z), 1);

        __double_decode_array_cleanup(&(p[element].base_link_p), 1);

        __double_decode_array_cleanup(&(p[element].HP), 1);

        __double_decode_array_cleanup(&(p[element].LSP), 1);

        __double_decode_array_cleanup(&(p[element].LEP), 1);

        __double_decode_array_cleanup(&(p[element].LWP), 1);

        __double_decode_array_cleanup(&(p[element].RSP), 1);

        __double_decode_array_cleanup(&(p[element].REP), 1);

        __double_decode_array_cleanup(&(p[element].RWP), 1);

        __double_decode_array_cleanup(&(p[element].LHP), 1);

        __double_decode_array_cleanup(&(p[element].LKP), 1);

        __double_decode_array_cleanup(&(p[element].LAP), 1);

        __double_decode_array_cleanup(&(p[element].RHP), 1);

        __double_decode_array_cleanup(&(p[element].RKP), 1);

        __double_decode_array_cleanup(&(p[element].RAP), 1);

        __double_decode_array_cleanup(&(p[element].base_link_xdot), 1);

        __double_decode_array_cleanup(&(p[element].base_link_zdot), 1);

        __double_decode_array_cleanup(&(p[element].base_link_pdot), 1);

        __double_decode_array_cleanup(&(p[element].HPdot), 1);

        __double_decode_array_cleanup(&(p[element].LSPdot), 1);

        __double_decode_array_cleanup(&(p[element].LEPdot), 1);

        __double_decode_array_cleanup(&(p[element].LWPdot), 1);

        __double_decode_array_cleanup(&(p[element].RSPdot), 1);

        __double_decode_array_cleanup(&(p[element].REPdot), 1);

        __double_decode_array_cleanup(&(p[element].RWPdot), 1);

        __double_decode_array_cleanup(&(p[element].LHPdot), 1);

        __double_decode_array_cleanup(&(p[element].LKPdot), 1);

        __double_decode_array_cleanup(&(p[element].LAPdot), 1);

        __double_decode_array_cleanup(&(p[element].RHPdot), 1);

        __double_decode_array_cleanup(&(p[element].RKPdot), 1);

        __double_decode_array_cleanup(&(p[element].RAPdot), 1);

    }
    return 0;
}

int lcmt_hubo_saggital_state_decode(const void *buf, int offset, int maxlen, lcmt_hubo_saggital_state *p)
{
    int pos = 0, thislen;
    int64_t hash = __lcmt_hubo_saggital_state_get_hash();

    int64_t this_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &this_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (this_hash != hash) return -1;

    thislen = __lcmt_hubo_saggital_state_decode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int lcmt_hubo_saggital_state_decode_cleanup(lcmt_hubo_saggital_state *p)
{
    return __lcmt_hubo_saggital_state_decode_array_cleanup(p, 1);
}

int __lcmt_hubo_saggital_state_clone_array(const lcmt_hubo_saggital_state *p, lcmt_hubo_saggital_state *q, int elements)
{
    int element;
    for (element = 0; element < elements; element++) {

        __int64_t_clone_array(&(p[element].timestamp), &(q[element].timestamp), 1);

        __double_clone_array(&(p[element].base_link_x), &(q[element].base_link_x), 1);

        __double_clone_array(&(p[element].base_link_z), &(q[element].base_link_z), 1);

        __double_clone_array(&(p[element].base_link_p), &(q[element].base_link_p), 1);

        __double_clone_array(&(p[element].HP), &(q[element].HP), 1);

        __double_clone_array(&(p[element].LSP), &(q[element].LSP), 1);

        __double_clone_array(&(p[element].LEP), &(q[element].LEP), 1);

        __double_clone_array(&(p[element].LWP), &(q[element].LWP), 1);

        __double_clone_array(&(p[element].RSP), &(q[element].RSP), 1);

        __double_clone_array(&(p[element].REP), &(q[element].REP), 1);

        __double_clone_array(&(p[element].RWP), &(q[element].RWP), 1);

        __double_clone_array(&(p[element].LHP), &(q[element].LHP), 1);

        __double_clone_array(&(p[element].LKP), &(q[element].LKP), 1);

        __double_clone_array(&(p[element].LAP), &(q[element].LAP), 1);

        __double_clone_array(&(p[element].RHP), &(q[element].RHP), 1);

        __double_clone_array(&(p[element].RKP), &(q[element].RKP), 1);

        __double_clone_array(&(p[element].RAP), &(q[element].RAP), 1);

        __double_clone_array(&(p[element].base_link_xdot), &(q[element].base_link_xdot), 1);

        __double_clone_array(&(p[element].base_link_zdot), &(q[element].base_link_zdot), 1);

        __double_clone_array(&(p[element].base_link_pdot), &(q[element].base_link_pdot), 1);

        __double_clone_array(&(p[element].HPdot), &(q[element].HPdot), 1);

        __double_clone_array(&(p[element].LSPdot), &(q[element].LSPdot), 1);

        __double_clone_array(&(p[element].LEPdot), &(q[element].LEPdot), 1);

        __double_clone_array(&(p[element].LWPdot), &(q[element].LWPdot), 1);

        __double_clone_array(&(p[element].RSPdot), &(q[element].RSPdot), 1);

        __double_clone_array(&(p[element].REPdot), &(q[element].REPdot), 1);

        __double_clone_array(&(p[element].RWPdot), &(q[element].RWPdot), 1);

        __double_clone_array(&(p[element].LHPdot), &(q[element].LHPdot), 1);

        __double_clone_array(&(p[element].LKPdot), &(q[element].LKPdot), 1);

        __double_clone_array(&(p[element].LAPdot), &(q[element].LAPdot), 1);

        __double_clone_array(&(p[element].RHPdot), &(q[element].RHPdot), 1);

        __double_clone_array(&(p[element].RKPdot), &(q[element].RKPdot), 1);

        __double_clone_array(&(p[element].RAPdot), &(q[element].RAPdot), 1);

    }
    return 0;
}

lcmt_hubo_saggital_state *lcmt_hubo_saggital_state_copy(const lcmt_hubo_saggital_state *p)
{
    lcmt_hubo_saggital_state *q = (lcmt_hubo_saggital_state*) malloc(sizeof(lcmt_hubo_saggital_state));
    __lcmt_hubo_saggital_state_clone_array(p, q, 1);
    return q;
}

void lcmt_hubo_saggital_state_destroy(lcmt_hubo_saggital_state *p)
{
    __lcmt_hubo_saggital_state_decode_array_cleanup(p, 1);
    free(p);
}

int lcmt_hubo_saggital_state_publish(lcm_t *lc, const char *channel, const lcmt_hubo_saggital_state *p)
{
      int max_data_size = lcmt_hubo_saggital_state_encoded_size (p);
      uint8_t *buf = (uint8_t*) malloc (max_data_size);
      if (!buf) return -1;
      int data_size = lcmt_hubo_saggital_state_encode (buf, 0, max_data_size, p);
      if (data_size < 0) {
          free (buf);
          return data_size;
      }
      int status = lcm_publish (lc, channel, buf, data_size);
      free (buf);
      return status;
}

struct _lcmt_hubo_saggital_state_subscription_t {
    lcmt_hubo_saggital_state_handler_t user_handler;
    void *userdata;
    lcm_subscription_t *lc_h;
};
static
void lcmt_hubo_saggital_state_handler_stub (const lcm_recv_buf_t *rbuf,
                            const char *channel, void *userdata)
{
    int status;
    lcmt_hubo_saggital_state p;
    memset(&p, 0, sizeof(lcmt_hubo_saggital_state));
    status = lcmt_hubo_saggital_state_decode (rbuf->data, 0, rbuf->data_size, &p);
    if (status < 0) {
        fprintf (stderr, "error %d decoding lcmt_hubo_saggital_state!!!\n", status);
        return;
    }

    lcmt_hubo_saggital_state_subscription_t *h = (lcmt_hubo_saggital_state_subscription_t*) userdata;
    h->user_handler (rbuf, channel, &p, h->userdata);

    lcmt_hubo_saggital_state_decode_cleanup (&p);
}

lcmt_hubo_saggital_state_subscription_t* lcmt_hubo_saggital_state_subscribe (lcm_t *lcm,
                    const char *channel,
                    lcmt_hubo_saggital_state_handler_t f, void *userdata)
{
    lcmt_hubo_saggital_state_subscription_t *n = (lcmt_hubo_saggital_state_subscription_t*)
                       malloc(sizeof(lcmt_hubo_saggital_state_subscription_t));
    n->user_handler = f;
    n->userdata = userdata;
    n->lc_h = lcm_subscribe (lcm, channel,
                                 lcmt_hubo_saggital_state_handler_stub, n);
    if (n->lc_h == NULL) {
        fprintf (stderr,"couldn't reg lcmt_hubo_saggital_state LCM handler!\n");
        free (n);
        return NULL;
    }
    return n;
}

int lcmt_hubo_saggital_state_subscription_set_queue_capacity (lcmt_hubo_saggital_state_subscription_t* subs,
                              int num_messages)
{
    return lcm_subscription_set_queue_capacity (subs->lc_h, num_messages);
}

int lcmt_hubo_saggital_state_unsubscribe(lcm_t *lcm, lcmt_hubo_saggital_state_subscription_t* hid)
{
    int status = lcm_unsubscribe (lcm, hid->lc_h);
    if (0 != status) {
        fprintf(stderr,
           "couldn't unsubscribe lcmt_hubo_saggital_state_handler %p!\n", hid);
        return -1;
    }
    free (hid);
    return 0;
}

