/** THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
 * BY HAND!!
 *
 * Generated by lcm-gen
 **/

#include <stdint.h>
#include <stdlib.h>
#include <lcm/lcm_coretypes.h>
#include <lcm/lcm.h>

#ifndef _lcmt_hubo_state_h
#define _lcmt_hubo_state_h

#ifdef __cplusplus
extern "C" {
#endif

typedef struct _lcmt_hubo_state lcmt_hubo_state;
struct _lcmt_hubo_state
{
    int64_t    timestamp;
    double     base_link_x;
    double     base_link_y;
    double     base_link_z;
    double     base_link_roll;
    double     base_link_pitch;
    double     base_link_yaw;
    double     HipYaw;
    double     HY;
    double     HR;
    double     HP;
    double     STATE_LSP;
    double     STATE_LSR;
    double     STATE_LSY;
    double     STATE_LEP;
    double     STATE_LWY;
    double     STATE_LWR;
    double     STATE_LWP;
    double     STATE_RSP;
    double     STATE_RSR;
    double     STATE_RSY;
    double     STATE_REP;
    double     STATE_RWY;
    double     STATE_RWR;
    double     STATE_RWP;
    double     STATE_LHY;
    double     STATE_LHR;
    double     STATE_LHP;
    double     STATE_LKP;
    double     STATE_LAP;
    double     STATE_LAR;
    double     STATE_RHY;
    double     STATE_RHR;
    double     STATE_RHP;
    double     STATE_RKP;
    double     STATE_RAP;
    double     STATE_RAR;
    double     base_link_xdot;
    double     base_link_ydot;
    double     base_link_zdot;
    double     base_link_rolldot;
    double     base_link_pitchdot;
    double     base_link_yawdot;
    double     HipYawdot;
    double     HYdot;
    double     HRdot;
    double     HPdot;
    double     LSPdot;
    double     LSRdot;
    double     LSYdot;
    double     LEPdot;
    double     LWYdot;
    double     LWRdot;
    double     LWPdot;
    double     RSPdot;
    double     RSRdot;
    double     RSYdot;
    double     REPdot;
    double     RWYdot;
    double     RWRdot;
    double     RWPdot;
    double     LHYdot;
    double     LHRdot;
    double     LHPdot;
    double     LKPdot;
    double     LAPdot;
    double     LARdot;
    double     RHYdot;
    double     RHRdot;
    double     RHPdot;
    double     RKPdot;
    double     RAPdot;
    double     RARdot;
};

lcmt_hubo_state   *lcmt_hubo_state_copy(const lcmt_hubo_state *p);
void lcmt_hubo_state_destroy(lcmt_hubo_state *p);

typedef struct _lcmt_hubo_state_subscription_t lcmt_hubo_state_subscription_t;
typedef void(*lcmt_hubo_state_handler_t)(const lcm_recv_buf_t *rbuf,
             const char *channel, const lcmt_hubo_state *msg, void *user);

int lcmt_hubo_state_publish(lcm_t *lcm, const char *channel, const lcmt_hubo_state *p);
lcmt_hubo_state_subscription_t* lcmt_hubo_state_subscribe(lcm_t *lcm, const char *channel, lcmt_hubo_state_handler_t f, void *userdata);
int lcmt_hubo_state_unsubscribe(lcm_t *lcm, lcmt_hubo_state_subscription_t* hid);
int lcmt_hubo_state_subscription_set_queue_capacity(lcmt_hubo_state_subscription_t* subs,
                              int num_messages);


int  lcmt_hubo_state_encode(void *buf, int offset, int maxlen, const lcmt_hubo_state *p);
int  lcmt_hubo_state_decode(const void *buf, int offset, int maxlen, lcmt_hubo_state *p);
int  lcmt_hubo_state_decode_cleanup(lcmt_hubo_state *p);
int  lcmt_hubo_state_encoded_size(const lcmt_hubo_state *p);

// LCM support functions. Users should not call these
int64_t __lcmt_hubo_state_get_hash(void);
int64_t __lcmt_hubo_state_hash_recursive(const __lcm_hash_ptr *p);
int     __lcmt_hubo_state_encode_array(void *buf, int offset, int maxlen, const lcmt_hubo_state *p, int elements);
int     __lcmt_hubo_state_decode_array(const void *buf, int offset, int maxlen, lcmt_hubo_state *p, int elements);
int     __lcmt_hubo_state_decode_array_cleanup(lcmt_hubo_state *p, int elements);
int     __lcmt_hubo_state_encoded_array_size(const lcmt_hubo_state *p, int elements);
int     __lcmt_hubo_state_clone_array(const lcmt_hubo_state *p, lcmt_hubo_state *q, int elements);

#ifdef __cplusplus
}
#endif

#endif
